### ISSUE TITLE
We need a method for analyzing the weights

### ISSUE THREAD

**Issue by millerh1** [dmontemayor/jdrfmetabo#13]
We need a method for analyzing the weights of the AE and seeing the degree to which each pathway contributes to the LVs

**Comment by Julian-Borbeck** [comment]
This is fairly easy, basically model.components_decomposition_ does that. The question now becomes on what this function should return. In my opinion you should be able to specify a LV and get a sorted pandas series with all pathways with a contribution above a specified cutoff value. Would this be along the lines of what you imagined?

**Comment by millerh1** [comment]
Done
