### ISSUE TITLE
Need intelligent pre-packaging of pathway data-sets

### ISSUE THREAD

**Issue by millerh1** [dmontemayor/jdrfmetabo#6]
How large would a sparse matrix representation of this be? If too large, can we host in Zenodo? Should the user have the option to specify custom pathways?

**Comment by dmontemayor** [comment]
I think an option for custom omic indices is a good idea. It should be easy to implement with a dictionary - with omics as the keys and the value as a list of pathways (custom indices) that omic participates in. No need for a sparse matrix.

**Comment by millerh1** [comment]
wontfix
